# Configuration for probot-no-response - https://github.com/probot/no-response

name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          # Number of days of inactivity before an Issue is closed for lack of response
          daysUntilClose: 3
          # Label requiring a response
          responseRequiredLabel: status.info-needed
          # Comment to post when closing an Issue for lack of response. Set to `false` to disable
          closeComment: >
            This issue has been automatically closed because there has been no response to our request for more information from the original author. We don't have enough information to take action. Please reopen if the question from the maintainer has been answered and the issue is still valid.
