import _ from "lodash";
import * as v from "@badrap/valita";
import { ok, err } from "neverthrow";
import type { NotePropsByIdDict, DuplicateNoteBehavior } from "./types";
// import type { TreeMenu, TreeMenuNode } from "./util/treeUtil";
import { parse } from "./parse";

type Option<T> = T | undefined;

const noteLiteral = v.literal("note");
const autogeneratedLiteral = v.literal("autogenerated");
const categoryLiteral = v.literal("category");

const sidebarItemNote = v.object({
  type: noteLiteral,
  id: v.string(),
  label: v.string(),
});

// type SidebarItemNote = v.Infer<typeof sidebarItemNote>;

const sidebarItemAutogenerated = v.object({
  type: autogeneratedLiteral,
  id: v.union(v.literal("root"), v.string()),
});

type SidebarItemAutogenerated = v.Infer<typeof sidebarItemAutogenerated>;

const sidebarItemCategoryLinkNote = v.object({
  type: noteLiteral,
  id: v.string(),
});

type SidebarItemCategory = {
  type: "category";
  label: string;
  items: SidebarItem[];
};

const sidebarItemCategory: v.Type<SidebarItemCategory> = v.lazy(() =>
  v.object({
    type: categoryLiteral,
    label: v.string(),
    items: v.array(v.lazy(() => sidebarItem)),
    link: sidebarItemCategoryLinkNote,
  })
);

const sidebarItem = v.union(
  sidebarItemCategory,
  sidebarItemNote,
  sidebarItemAutogenerated
);

type SidebarItem = v.Infer<typeof sidebarItem>;

const sidebarItemProcessed = v.union(sidebarItemCategory, sidebarItemNote);

type SidebarItemProcessed = v.Infer<typeof sidebarItemProcessed>;

const sidebar = v.array(sidebarItem);
const sidebarProcessed = v.array(sidebarItemProcessed);

type Sidebar = v.Infer<typeof sidebar>;
type SidebarProcessed = v.Infer<typeof sidebarProcessed>;

const sidebars = v.record(sidebar);
const sidebarsProcessed = v.record(sidebarProcessed);

type Sidebars = v.Infer<typeof sidebars>;
type SidebarsProcessed = v.Infer<typeof sidebarsProcessed>;

type SidebarItemsGeneratorParams = {
  item: SidebarItemAutogenerated;
  notes: NotePropsByIdDict;
  duplicateNoteBehavior?: DuplicateNoteBehavior;
};
type SidebarItemsGenerator = (
  params: SidebarItemsGeneratorParams
) => SidebarItemProcessed[];

type SidebarOptions = {
  duplicateNoteBehavior?: DuplicateNoteBehavior;
  notes: NotePropsByIdDict;
};

export const DefaultSidebars: Sidebars = {
  defaultSidebar: [
    {
      type: "autogenerated",
      id: "root",
    },
  ],
};

export const DisabledSidebars: Sidebars = {};

const defaultSidbarItemsGenerator: SidebarItemsGenerator = ({
  item,
  notes,
  duplicateNoteBehavior,
}) => {
  function findHierarchySource() {
    const possibleHierarchySources = [
      // 1. check if reference uses `id`.
      notes[item.id] ??
        // 2. find note based on `fname`
        Object.values(notes).filter((note) => {
          return note.fname === item.id;
        }),
    ].flat();

    const hasDuplicates = possibleHierarchySources.length > 1;

    const note =
      // if more than a single note was found than use `duplicateNoteBehavior` to select a single note.
      (hasDuplicates &&
        do_(() => {
          const map = new Map(
            possibleHierarchySources.map((note) => [
              note.vault.name ?? note.vault.fsPath,
              note,
            ])
          );
          return getPriorityVaults(duplicateNoteBehavior)
            ?.filter((vaultName) => map.has(vaultName))
            .map((vaultName) => map.get(vaultName))
            .at(0);
        })) ||
      // default to first
      possibleHierarchySources.at(0);

    return note;
  }

  const hierarchySource = findHierarchySource();
  console.log("hierarchySource:", hierarchySource);

  return [];
};

function processSiderbar(
  sidebar: Sidebar,
  { notes, duplicateNoteBehavior }: SidebarOptions
): SidebarProcessed {
  function processAutoGeneratedItem(item: SidebarItemAutogenerated) {
    return (
      // possible option for control from outside
      // sidebarItemsGenerator?.({ item, notes, duplicateNoteBehavior }) ??
      defaultSidbarItemsGenerator({ item, notes, duplicateNoteBehavior })
    );
  }
  function processItem(item: SidebarItem): SidebarItemProcessed[] {
    if (item.type === "category") {
      return [
        {
          ...item,
          items: item.items.map(processItem).flat(),
        },
      ];
    }
    if (item.type === "autogenerated") {
      return processAutoGeneratedItem(item);
    }
    return [item];
  }

  return sidebar.map(processItem).flat();
}

function processSidebars(
  sidebars: Sidebars,
  options: SidebarOptions
): SidebarsProcessed {
  const processedSidebars = _.mapValues(sidebars, (sidebar) =>
    processSiderbar(sidebar, options)
  );
  return processedSidebars;
}

// function preProcessSidebars(sidebars: Sidebars) {}

export async function getSidebars(input: unknown, options: SidebarOptions) {
  const sidebarsConfigResult = parse(sidebars, input);
  if (sidebarsConfigResult.isOk()) {
    return ok(processSidebars(sidebarsConfigResult.value, options));
  }
  return err(sidebarsConfigResult);
}

function getPriorityVaults(
  duplicateNoteBehavior?: DuplicateNoteBehavior
): Option<string[]> {
  if (Array.isArray(duplicateNoteBehavior?.payload)) {
    return duplicateNoteBehavior?.payload;
  }
  const vaultName = duplicateNoteBehavior?.payload.vault?.name;
  if (vaultName) {
    return [vaultName];
  }
  return undefined;
}

function do_<T>(f: () => T): T {
  return f();
}
