name: CI Setup

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      node-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  setup-ci:
    name: Setup CI Environment
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Gather environment data
        run: |
          ${{ inputs.env }}
          node --version
          npm --version
          yarn --version

      - uses: actions/setup-node@v2
        with:
          node-version: "${{ inputs.node-version }}"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      # Publish tests won't work if we haven't configured our committer details.
      - name: Configure Git user
        run: |
          git config --global user.name CI
          git config --global user.email ci@dendron.so

      - name: Restore typescript lib cache
        uses: actions/cache@v2
        id: ts-cache
        with:
          path: |
            packages/*/lib/*
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-22
          restore-keys: |
            ${{ runner.os }}-yarn-9
