name: CI Windows Test

on:
  push:
    branches:
      - chore/windows-ci-*
jobs:
  test:
    strategy:
      fail-fast: true

      matrix:
        os:
          - windows-latest
        node-version:
          - 14.x
          - 16.x
        suite:
          - cli
          - plugin

        include:
          - os: windows-latest
            env: Get-ChildItem Env:\
            versions: choco --version

    timeout-minutes: 40

    runs-on: ${{ matrix.os }}

    steps:
      - name: Gather environment data
        run: |
          ${{ matrix.env }}
          node --version
          npm --version
          yarn --version

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Node modules cache for Windows
        if: runner.os == 'Windows'
        uses: actions/cache@v3
        id: node-modules-cache-windows
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-17
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-8

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Publish tests won't work if we haven't configured our committer details.
      - name: Configure Git user
        run: |
          git config --global user.name CI
          git config --global user.email ci@dendron.so

      - name: Initialize
        run: yarn ci:init
        shell: bash

      - name: Run tests
        run: yarn ci:test:${{ matrix.suite }}
        timeout-minutes: 40
