name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.2
        with:
          repo-token: ${{ github.token }}
          configuration-path: .github/config/issue-labler/labler.yml
          not-before: "2020-02-21T00:00:00Z"
          enable-versioned-regex: 1
          versioned-regex: 'issue_labeler_regex_version=(\d+)'
