name: Publish to Nightly

on: workflow_dispatch
  # push:
  #   branches:
  #     - release/*
  #     - chore/ga-build-automation
  

jobs:
  build:
    environment: plugin # TODO: Switch to plugin-development when that environment is ready.
    strategy:
      fail-fast: true

    timeout-minutes: 30

    runs-on: ubuntu-latest

    steps:
      - name: Gather environment data
        run: |
          node --version
          npm --version
          yarn --version

      - name: Configure Git user
        run: |
          git config --global user.name CI
          git config --global user.email ci@dendron.so

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version:  14.x

      - name: Yarn Setup
        run: yarn setup
      
      # TODO: Corect DENDRON_RELEASE_VERSION Variable name
      - name: Build the VSIX
        env: 
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          echo "DENDRON_RELEASE_VERSION=`cat meta.json | jq -r '.["@dendronhq/plugin-core"]' | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}'`" >> $GITHUB_ENV
          yarn build:prerelease:remote:ci

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vsix
          path: ./packages/plugin-core/*.vsix

      - name: Publish to VS Code Marketplace
        env: 
          VSCE_PAT: ${{ secrets.VSCODE_PUBLISH_PWD }}
        run: yarn deploy:vscode
          
      - name: Publish to Open VSX Marketplace
        env: 
          OVSX_PAT: ${{ secrets.VSCODIUM_PUBLISH_PWD }}
        run: yarn deploy:ovsx